name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job para a etapa de Build
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checar o código
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Construir a imagem Docker
      run: |
        docker-compose -f docker-compose.yml build

  train:
    runs-on: ubuntu-latest
    needs: build 

    steps:
    - name: Checar o código
      uses: actions/checkout@v2

    - name: Instalar dependências
      run: |
        docker-compose run --rm airflow pip install -r requirements.txt

    - name: Treinar o modelo
      run: |
        docker-compose run --rm airflow python app/train_model.py 

  # Job para a etapa de Teste
  test:
    runs-on: ubuntu-latest
    needs: train

    steps:
    - name: Checar o código
      uses: actions/checkout@v2

    - name: Rodar os testes
      run: |
        docker-compose run --rm airflow pip install -r requirements.txt

    - name: Rodar os testes
      run: |
        docker-compose run --rm airflow pytest tests/test_bitcoin_pipeline.py

  # Job para a etapa de Deploy
  deploy:
    runs-on: ubuntu-latest
    needs: test 

    steps:
    - name: Checar o código
      uses: actions/checkout@v2

    - name: Deploy para produção
      run: |
        docker-compose up -d
